// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ganwdxgmeykbwkqungga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhbndkeGdtZXlrYndrcXVuZ2dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMzIyMzIsImV4cCI6MjA3MjkwODIzMn0.gyULV2AJRyiAiVd1_JPEJuUDSlMBEN-Uw3vN9VQKVAc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});